gui:
  language: "zh-TW"
  showIcons: true
os:
  open: "open {{filename}}"
  editPreset: "nvim"
confirmOnQuit: false
customCommands:
  - key: "w"
    prompts:
      - type: "Input"
        title: "Commit"
        initialValue: "WIP"
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "files"
    description: "Commit message without verify"
  - key: "A"
    command: git commit --amend {{.Form.V}} --no-edit
    prompts:
      - type: "menu"
        title: "Need verify ?"
        key: "V"
        options:
          - value: " "
            name: "Verify"
          - value: --no-verify
            name: "Skip"
    context: "files"
    description: "Amend commit"
  - key: "<c-p>"
    command: git cherry-pick -x {{.SelectedSubCommit.Sha}}
    prompts:
      - type: "confirm"
        title: "Cherry-pick {{.SelectedSubCommit.Name}} ?"
    context: "subCommits"
    description: "Cherry-pick commit with sha"
  - key: "F"
    context: remotes
    command: "git fetch --prune origin --verbose"
    description: "Fetch remote branches"
  - key: "U"
    command: "git submodule update --remote --merge"
    context: "submodules"
    description: "Update submodules to remote"
